package Ej7;

import Ej7.modelo.Persona;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Main {
    public static void main(String[] args) {
        List<Persona> listPersona = trataDatos();
        // 1.	 Personas mayores de edad, que están cursando un curso que empieza por A y su nombre contiene una dieresis (¨)
        listPersona.stream()
                .filter(persona -> persona.getEdad() >= 18)
                .filter(persona -> persona.getCurso().startsWith("A"))
                .filter(persona -> persona.getNombre().contains("N"))
                .forEach(System.out::println);

        //2.	Personas con edades entre 20 y 25 años
        listPersona.stream()
                .filter(persona -> persona.getEdad() >= 20 && persona.getEdad() <= 25)
                .forEach(System.out::println);

        //3.	Muestra las personas que han aprobado el curso de POO
        listPersona.stream()
                .filter(persona -> persona.getNota() >= 5)
                .filter(persona -> persona.getCurso().equals("POO"))
                .forEach(System.out::println);

        //4.	Muestra el número de personas que hay matriculadas en cada curso.
        listPersona.stream()
                .collect(Collectors.groupingBy(Persona::getCurso, Collectors.counting()))
                .forEach((curso, numPersonas) -> System.out.println(curso + ": " + numPersonas));
        /*SOLUCION:
        {Java=80, Acceso a datos=52, Express=71, Patrones de diseño=47, odoo=63, PostgreSQL=68, react=45, NodeJs=66, Angular=62, sql=56, POO=73, XML=65, MySQL=65, JavaScript=55, Javascript=1, Oracle=65, BBDD=67}*/


    }

    private static List<Persona> trataDatos() {
        List<Persona> lista = new ArrayList<>();
        lista.add(new Persona(1, "Adélie", "Deinhard", "Angular", 10, 45));
        lista.add(new Persona(2, "Angélique", "Cloake", "sql", 10, 33));
        lista.add(new Persona(3, "Gaëlle", "Cheales", "Express", 5, 47));
        lista.add(new Persona(4, "Illustrée", "Maunton", "XML", 4, 68));
        lista.add(new Persona(5, "Gwenaëlle", "Flucks", "XML", 1, 27));
        lista.add(new Persona(6, "Kallisté", "Edington", "POO", 10, 60));
        lista.add(new Persona(7, "Åke", "Chern", "Angular", 1, 19));
        lista.add(new Persona(8, "Lèi", "De Mattei", "Oracle", 6, 23));
        lista.add(new Persona(9, "Tán", "Yarn", "Java", 1, 60));
        lista.add(new Persona(10, "Naéva", "Chase", "Java", 7, 22));
        lista.add(new Persona(11, "Clémence", "Klimas", "PostgreSQL", 6, 48));
        lista.add(new Persona(12, "Gisèle", "Vannucci", "POO", 4, 23));
        lista.add(new Persona(13, "Maïwenn", "Chevis", "XML", 7, 55));
        lista.add(new Persona(14, "Tán", "Keiling", "XML", 7, 48));
        lista.add(new Persona(15, "Mélinda", "Rasch", "JavaScript", 10, 40));
        lista.add(new Persona(16, "Méng", "Mabone", "Oracle", 6, 52));
        lista.add(new Persona(17, "Andrée", "Paxman", "Java", 2, 36));
        lista.add(new Persona(18, "Marie-ève", "Shrimptone", "POO", 7, 63));
        lista.add(new Persona(19, "Esbjörn", "Topaz", "react", 3, 59));
        lista.add(new Persona(20, "Aurélie", "Smedley", "POO", 9, 20));
        lista.add(new Persona(21, "Aimée", "Knaggs", "Oracle", 10, 62));
        lista.add(new Persona(22, "Audréanne", "Aubert", "Oracle", 7, 55));
        lista.add(new Persona(23, "Angèle", "Mair", "Patrones de diseño", 9, 38));
        lista.add(new Persona(24, "Estée", "Cosens", "PostgreSQL", 7, 39));
        lista.add(new Persona(25, "Nélie", "Poleye", "Express", 1, 52));
        lista.add(new Persona(26, "Pål", "Mounsey", "odoo", 6, 49));
        lista.add(new Persona(27, "Lucrèce", "Cranton", "Java", 8, 55));
        lista.add(new Persona(28, "Åsa", "Cronchey", "NodeJs", 8, 49));
        lista.add(new Persona(29, "Marylène", "Myott", "Acceso a datos", 6, 43));
        lista.add(new Persona(30, "Méthode", "Schulz", "Angular", 3, 75));
        lista.add(new Persona(31, "Réjane", "Blowfelde", "POO", 9, 32));
        lista.add(new Persona(32, "Måns", "Dunnion", "react", 1, 38));
        lista.add(new Persona(33, "Régine", "Freemantle", "Angular", 9, 37));
        lista.add(new Persona(34, "Pélagie", "Riccardi", "POO", 8, 45));
        lista.add(new Persona(35, "Måns", "Waldren", "POO", 1, 23));
        lista.add(new Persona(36, "Clélia", "McClounan", "Angular", 10, 40));
        lista.add(new Persona(37, "Nadège", "Praundl", "Patrones de diseño", 5, 24));
        lista.add(new Persona(38, "Hélèna", "McCorley", "sql", 4, 51));
        lista.add(new Persona(39, "Yè", "Beaby", "Oracle", 3, 75));
        lista.add(new Persona(40, "Dà", "Bickerton", "Express", 2, 67));
        lista.add(new Persona(41, "Lyséa", "Maylard", "XML", 3, 67));
        lista.add(new Persona(42, "Joséphine", "Milsom", "Angular", 9, 67));
        lista.add(new Persona(43, "Illustrée", "Egre", "Express", 8, 32));
        lista.add(new Persona(44, "Océane", "Nunnery", "Express", 4, 40));
        lista.add(new Persona(45, "Vénus", "Cakes", "Oracle", 10, 23));
        lista.add(new Persona(46, "Méghane", "Wonter", "Express", 8, 34));
        lista.add(new Persona(47, "Thérèse", "Godbolt", "XML", 4, 38));
        lista.add(new Persona(48, "Renée", "Matias", "sql", 3, 70));
        lista.add(new Persona(49, "Pénélope", "Barbrick", "MySQL", 5, 61));
        lista.add(new Persona(50, "Björn", "Massei", "Oracle", 6, 62));
        lista.add(new Persona(51, "Maïwenn", "Boughen", "NodeJs", 4, 61));
        lista.add(new Persona(52, "Léandre", "Wetherhead", "Express", 5, 22));
        lista.add(new Persona(53, "Marie-josée", "Gilmour", "JavaScript", 1, 65));
        lista.add(new Persona(54, "Irène", "Allabarton", "Oracle", 9, 66));
        lista.add(new Persona(55, "Yú", "Bengtsen", "Express", 7, 26));
        lista.add(new Persona(56, "Adélie", "Linsay", "Angular", 9, 38));
        lista.add(new Persona(57, "Adèle", "Duferie", "BBDD", 5, 44));
        lista.add(new Persona(58, "Léane", "Sotheby", "PostgreSQL", 9, 63));
        lista.add(new Persona(59, "Gaétane", "Drinkhall", "MySQL", 3, 53));
        lista.add(new Persona(60, "Faîtes", "Leverton", "BBDD", 6, 50));
        lista.add(new Persona(61, "Judicaël", "Cubbin", "XML", 7, 32));
        lista.add(new Persona(62, "Véronique", "Whyte", "odoo", 9, 33));
        lista.add(new Persona(63, "Josée", "Sawers", "PostgreSQL", 6, 71));
        lista.add(new Persona(64, "Naëlle", "Puckett", "react", 3, 75));
        lista.add(new Persona(65, "Håkan", "Tolfrey", "Java", 4, 24));
        lista.add(new Persona(66, "Maëline", "Everard", "PostgreSQL", 3, 18));
        lista.add(new Persona(67, "Michèle", "Stempe", "Angular", 6, 47));
        lista.add(new Persona(68, "Görel", "Elcocks", "odoo", 3, 35));
        lista.add(new Persona(69, "Yóu", "Branston", "Angular", 8, 31));
        lista.add(new Persona(70, "Léandre", "Bertelsen", "POO", 3, 32));
        lista.add(new Persona(71, "Estée", "Stoyell", "MySQL", 8, 45));
        lista.add(new Persona(72, "Stévina", "Trevett", "JavaScript", 7, 30));
        lista.add(new Persona(73, "Kù", "Sherman", "Express", 9, 29));
        lista.add(new Persona(74, "Léandre", "Brewin", "Java", 10, 51));
        lista.add(new Persona(75, "Lyséa", "Meineken", "JavaScript", 10, 30));
        lista.add(new Persona(76, "Aimée", "Knowler", "BBDD", 9, 43));
        lista.add(new Persona(77, "Néhémie", "Fennessy", "Oracle", 3, 38));
        lista.add(new Persona(78, "Frédérique", "Baack", "MySQL", 8, 27));
        lista.add(new Persona(79, "Thérèse", "Pemberton", "sql", 5, 39));
        lista.add(new Persona(80, "Bérénice", "Lintot", "BBDD", 10, 44));
        lista.add(new Persona(81, "Annotés", "Skupinski", "NodeJs", 4, 59));
        lista.add(new Persona(82, "Bérangère", "Hattoe", "Java", 6, 75));
        lista.add(new Persona(83, "Angélique", "Goldin", "sql", 6, 24));
        lista.add(new Persona(84, "Eliès", "Mulleary", "sql", 8, 49));
        lista.add(new Persona(85, "Océanne", "Pischof", "JavaScript", 4, 21));
        lista.add(new Persona(86, "Marylène", "Chene", "BBDD", 4, 64));
        lista.add(new Persona(87, "Séréna", "Blakden", "react", 5, 26));
        lista.add(new Persona(88, "Vénus", "Oats", "Express", 7, 39));
        lista.add(new Persona(89, "Pål", "McQuorkel", "react", 8, 72));
        lista.add(new Persona(90, "Styrbjörn", "Probets", "Java", 8, 58));
        lista.add(new Persona(91, "Adélie", "Drepp", "odoo", 6, 38));
        lista.add(new Persona(92, "Frédérique", "Saur", "POO", 9, 71));
        lista.add(new Persona(93, "Wá", "Dorot", "POO", 8, 73));
        lista.add(new Persona(94, "Kù", "Marikhin", "Java", 7, 47));
        lista.add(new Persona(95, "Anaé", "Darwent", "Acceso a datos", 4, 21));
        lista.add(new Persona(96, "Maïlys", "Pawnsford", "Acceso a datos", 4, 30));
        lista.add(new Persona(97, "Annotée", "Tales", "odoo", 2, 44));
        lista.add(new Persona(98, "Maëlys", "Crosgrove", "Express", 4, 63));
        lista.add(new Persona(99, "Eléonore", "Christley", "POO", 2, 31));
        lista.add(new Persona(100, "Lyséa", "Magnay", "MySQL", 7, 23));
        lista.add(new Persona(101, "Vénus", "Hannah", "POO", 9, 52));
        lista.add(new Persona(102, "Loïs", "Rodda", "PostgreSQL", 5, 28));
        lista.add(new Persona(103, "Cunégonde", "Robic", "PostgreSQL", 3, 27));
        lista.add(new Persona(104, "Eliès", "Roddick", "sql", 2, 61));
        lista.add(new Persona(105, "Mylène", "Dunsford", "Java", 10, 67));
        lista.add(new Persona(106, "Aí", "Antliff", "Oracle", 8, 46));
        lista.add(new Persona(107, "Thérèse", "Chiese", "BBDD", 6, 69));
        lista.add(new Persona(108, "Maëlann", "Crayden", "Angular", 6, 55));
        lista.add(new Persona(109, "Adélaïde", "O'Howbane", "react", 10, 36));
        lista.add(new Persona(110, "Åsa", "Yesson", "Acceso a datos", 2, 27));
        lista.add(new Persona(111, "Thérèse", "Theaker", "NodeJs", 2, 48));
        lista.add(new Persona(112, "Cléa", "Caston", "odoo", 1, 18));
        lista.add(new Persona(113, "Célestine", "Hensmans", "BBDD", 9, 25));
        lista.add(new Persona(114, "Östen", "Pusey", "odoo", 6, 61));
        lista.add(new Persona(115, "Yóu", "Scudder", "PostgreSQL", 3, 61));
        lista.add(new Persona(116, "Méthode", "Knolles-Green", "Java", 7, 74));
        lista.add(new Persona(117, "Intéressant", "Threlkeld", "POO", 5, 52));
        lista.add(new Persona(118, "Méthode", "Hanway", "NodeJs", 3, 36));
        lista.add(new Persona(119, "Lauréna", "Dalyiel", "POO", 2, 30));
        lista.add(new Persona(120, "Gwenaëlle", "Jerdan", "PostgreSQL", 5, 67));
        lista.add(new Persona(121, "Intéressant", "Le Prevost", "POO", 9, 27));
        lista.add(new Persona(122, "Séverine", "Blakelock", "react", 5, 22));
        lista.add(new Persona(123, "Océane", "Leinthall", "Acceso a datos", 8, 24));
        lista.add(new Persona(124, "Maï", "Wileman", "PostgreSQL", 7, 39));
        lista.add(new Persona(125, "Bécassine", "Kinset", "XML", 2, 44));
        lista.add(new Persona(126, "Mélinda", "Batey", "Acceso a datos", 2, 66));
        lista.add(new Persona(127, "Naëlle", "Fellini", "Oracle", 9, 37));
        lista.add(new Persona(128, "Chloé", "Bungey", "Angular", 7, 18));
        lista.add(new Persona(129, "Annotés", "Amesbury", "POO", 2, 70));
        lista.add(new Persona(130, "Naëlle", "Hallen", "BBDD", 1, 50));
        lista.add(new Persona(131, "Adélaïde", "Brodeau", "XML", 3, 18));
        lista.add(new Persona(132, "Marie-hélène", "Cheak", "Express", 4, 27));
        lista.add(new Persona(133, "Eliès", "Sygroves", "MySQL", 4, 40));
        lista.add(new Persona(134, "Stévina", "Allsebrook", "Oracle", 5, 36));
        lista.add(new Persona(135, "Tú", "Craigg", "Acceso a datos", 2, 59));
        lista.add(new Persona(136, "Mårten", "Alfuso", "XML", 4, 40));
        lista.add(new Persona(137, "Håkan", "Shalcros", "Angular", 6, 31));
        lista.add(new Persona(138, "Loïc", "Tanswell", "odoo", 4, 52));
        lista.add(new Persona(139, "Méthode", "Klimkin", "Java", 1, 40));
        lista.add(new Persona(140, "Ruì", "Sharp", "Oracle", 7, 31));
        lista.add(new Persona(141, "Ráo", "Kerford", "Angular", 9, 39));
        lista.add(new Persona(142, "Geneviève", "Ianni", "Express", 10, 54));
        lista.add(new Persona(143, "Yóu", "Creek", "MySQL", 3, 41));
        lista.add(new Persona(144, "Noëlla", "Dulwitch", "MySQL", 9, 49));
        lista.add(new Persona(145, "Cécilia", "McKerron", "sql", 2, 39));
        lista.add(new Persona(146, "Mén", "Boulder", "react", 8, 48));
        lista.add(new Persona(147, "Jú", "Arkill", "Acceso a datos", 4, 34));
        lista.add(new Persona(148, "Maëline", "Marriot", "MySQL", 3, 33));
        lista.add(new Persona(149, "Anaël", "Knuckles", "POO", 10, 32));
        lista.add(new Persona(150, "Naéva", "Devonish", "Oracle", 3, 25));
        lista.add(new Persona(151, "Zoé", "Deedes", "JavaScript", 8, 50));
        lista.add(new Persona(152, "Gisèle", "Beatens", "sql", 6, 72));
        lista.add(new Persona(153, "Anaïs", "Schoenrock", "PostgreSQL", 6, 34));
        lista.add(new Persona(154, "Nuó", "Costen", "BBDD", 6, 34));
        lista.add(new Persona(155, "Bérénice", "Jarvie", "Java", 1, 66));
        lista.add(new Persona(156, "Sòng", "Foster", "react", 9, 55));
        lista.add(new Persona(157, "Garçon", "Braferton", "Express", 2, 30));
        lista.add(new Persona(158, "Marie-noël", "Lamplough", "NodeJs", 9, 21));
        lista.add(new Persona(159, "Eloïse", "Beckwith", "MySQL", 10, 48));
        lista.add(new Persona(160, "Gaétane", "Fereday", "Patrones de diseño", 4, 35));
        lista.add(new Persona(161, "Bécassine", "Robiot", "odoo", 7, 59));
        lista.add(new Persona(162, "Loïs", "Von Brook", "BBDD", 4, 60));
        lista.add(new Persona(163, "Aimée", "Meagh", "Express", 9, 41));
        lista.add(new Persona(164, "Yú", "Huggett", "react", 7, 39));
        lista.add(new Persona(165, "Andréa", "Trott", "NodeJs", 10, 52));
        lista.add(new Persona(166, "Mahélie", "Mintrim", "JavaScript", 9, 70));
        lista.add(new Persona(167, "Méng", "Bollon", "BBDD", 2, 58));
        lista.add(new Persona(168, "Léandre", "Footer", "NodeJs", 7, 62));
        lista.add(new Persona(169, "Görel", "Houlston", "odoo", 8, 32));
        lista.add(new Persona(170, "Naëlle", "Baughn", "Express", 8, 24));
        lista.add(new Persona(171, "Océane", "Streetley", "Express", 1, 62));
        lista.add(new Persona(172, "Alizée", "Geane", "BBDD", 3, 31));
        lista.add(new Persona(173, "Eugénie", "Shirtcliffe", "Acceso a datos", 6, 62));
        lista.add(new Persona(174, "Andrée", "Maiden", "MySQL", 7, 42));
        lista.add(new Persona(175, "Clélia", "Rawlingson", "react", 2, 45));
        lista.add(new Persona(176, "Salomé", "Starcks", "Patrones de diseño", 5, 70));
        lista.add(new Persona(177, "Noëlla", "Zukierman", "MySQL", 9, 27));
        lista.add(new Persona(178, "Edmée", "Cofax", "JavaScript", 6, 57));
        lista.add(new Persona(179, "Gösta", "Hargreave", "Java", 8, 31));
        lista.add(new Persona(180, "Marie-thérèse", "Silson", "PostgreSQL", 9, 51));
        lista.add(new Persona(181, "Desirée", "Fortnam", "POO", 3, 69));
        lista.add(new Persona(182, "Tú", "Blas", "odoo", 8, 52));
        lista.add(new Persona(183, "Åslög", "Jedrzejewsky", "Java", 5, 28));
        lista.add(new Persona(184, "Danièle", "Ryrie", "BBDD", 9, 34));
        lista.add(new Persona(185, "Lauréna", "Lusted", "BBDD", 3, 58));
        lista.add(new Persona(186, "Bénédicte", "Easterbrook", "Angular", 5, 67));
        lista.add(new Persona(187, "Sòng", "Mollon", "Oracle", 3, 67));
        lista.add(new Persona(188, "Naëlle", "Borley", "BBDD", 4, 62));
        lista.add(new Persona(189, "Gaëlle", "Truran", "Patrones de diseño", 7, 59));
        lista.add(new Persona(190, "Camélia", "Whybrow", "Express", 2, 40));
        lista.add(new Persona(191, "Vénus", "Thombleson", "MySQL", 3, 47));
        lista.add(new Persona(192, "Léa", "Rodrigo", "Angular", 10, 58));
        lista.add(new Persona(193, "Östen", "Waple", "MySQL", 3, 38));
        lista.add(new Persona(194, "Aimée", "McNeillie", "Oracle", 4, 70));
        lista.add(new Persona(195, "Dafnée", "McCaghan", "XML", 8, 75));
        lista.add(new Persona(196, "Yénora", "Daintry", "sql", 3, 38));
        lista.add(new Persona(197, "Yénora", "Baldi", "XML", 2, 70));
        lista.add(new Persona(198, "Maïlis", "Bronger", "Patrones de diseño", 5, 63));
        lista.add(new Persona(199, "Andréa", "Redhouse", "Java", 2, 20));
        lista.add(new Persona(200, "Lén", "Waddell", "NodeJs", 10, 73));
        lista.add(new Persona(201, "Camélia", "Tebald", "Java", 9, 57));
        lista.add(new Persona(202, "Aloïs", "Boner", "POO", 10, 41));
        lista.add(new Persona(203, "Noëlla", "Dalgarnocht", "Oracle", 10, 74));
        lista.add(new Persona(204, "Esbjörn", "Axtens", "JavaScript", 1, 55));
        lista.add(new Persona(205, "Marie-josée", "Paten", "odoo", 10, 67));
        lista.add(new Persona(206, "Rachèle", "Swanton", "Acceso a datos", 10, 25));
        lista.add(new Persona(207, "André", "Selburn", "MySQL", 10, 42));
        lista.add(new Persona(208, "Irène", "Scrase", "Patrones de diseño", 3, 22));
        lista.add(new Persona(209, "Börje", "Humm", "Acceso a datos", 1, 23));
        lista.add(new Persona(210, "Örjan", "Wilkinson", "NodeJs", 5, 69));
        lista.add(new Persona(211, "Dà", "Oldacre", "Express", 1, 20));
        lista.add(new Persona(212, "Amélie", "Saunter", "NodeJs", 7, 67));
        lista.add(new Persona(213, "Judicaël", "Langfitt", "Express", 4, 31));
        lista.add(new Persona(214, "Mylène", "Arnaudet", "BBDD", 4, 54));
        lista.add(new Persona(215, "Aimée", "Lavall", "PostgreSQL", 8, 41));
        lista.add(new Persona(216, "Eliès", "Chatwood", "MySQL", 4, 34));
        lista.add(new Persona(217, "Maëly", "Kirkhouse", "POO", 8, 27));
        lista.add(new Persona(218, "André", "Dashkov", "Patrones de diseño", 6, 28));
        lista.add(new Persona(219, "Gaïa", "Kix", "Oracle", 1, 24));
        lista.add(new Persona(220, "Kallisté", "Grog", "Patrones de diseño", 6, 48));
        lista.add(new Persona(221, "Tú", "McElrea", "BBDD", 5, 19));
        lista.add(new Persona(222, "Maëlle", "Lesor", "XML", 7, 36));
        lista.add(new Persona(223, "Michèle", "Marielle", "Express", 4, 59));
        lista.add(new Persona(224, "Maïly", "Bunson", "JavaScript", 6, 50));
        lista.add(new Persona(225, "Mégane", "Foster", "BBDD", 9, 58));
        lista.add(new Persona(226, "Séréna", "Slatford", "Express", 3, 51));
        lista.add(new Persona(227, "Laïla", "Gaymer", "XML", 9, 57));
        lista.add(new Persona(228, "Eléa", "Cotterel", "odoo", 1, 54));
        lista.add(new Persona(229, "Cléa", "Scrooby", "MySQL", 2, 29));
        lista.add(new Persona(230, "Lén", "Creffield", "PostgreSQL", 4, 62));
        lista.add(new Persona(231, "Eloïse", "Castell", "odoo", 8, 52));
        lista.add(new Persona(232, "Yáo", "Windham", "Acceso a datos", 2, 68));
        lista.add(new Persona(233, "Méline", "Mathou", "MySQL", 7, 40));
        lista.add(new Persona(234, "Régine", "Wafer", "JavaScript", 9, 35));
        lista.add(new Persona(235, "Gaëlle", "Popov", "Java", 3, 27));
        lista.add(new Persona(236, "Åslög", "Berriball", "Express", 4, 25));
        lista.add(new Persona(237, "Irène", "Borg-Bartolo", "Patrones de diseño", 6, 65));
        lista.add(new Persona(238, "Maïly", "Tomaszek", "NodeJs", 10, 24));
        lista.add(new Persona(239, "Valérie", "Walkley", "Java", 1, 20));
        lista.add(new Persona(240, "Daphnée", "Merritt", "Patrones de diseño", 4, 67));
        lista.add(new Persona(241, "Léone", "Capponeer", "Java", 4, 69));
        lista.add(new Persona(242, "Cécilia", "Grafton", "BBDD", 9, 54));
        lista.add(new Persona(243, "Ophélie", "McNeachtain", "XML", 10, 59));
        lista.add(new Persona(244, "Björn", "Obeney", "JavaScript", 5, 70));
        lista.add(new Persona(245, "Amélie", "Antalffy", "POO", 5, 60));
        lista.add(new Persona(246, "Angélique", "Greson", "sql", 10, 24));
        lista.add(new Persona(247, "Marylène", "Ca", "Java", 5, 64));
        lista.add(new Persona(248, "Léane", "Brookton", "MySQL", 5, 20));
        lista.add(new Persona(249, "Mylène", "Firks", "JavaScript", 6, 69));
        lista.add(new Persona(250, "Léonie", "Heaselgrave", "Java", 10, 40));
        lista.add(new Persona(251, "Estée", "Le Page", "JavaScript", 7, 73));
        lista.add(new Persona(252, "Östen", "Levesque", "XML", 1, 26));
        lista.add(new Persona(253, "Lèi", "Dermot", "POO", 1, 42));
        lista.add(new Persona(254, "Marie-hélène", "Campo", "Java", 8, 67));
        lista.add(new Persona(255, "Mélys", "Blatherwick", "NodeJs", 1, 22));
        lista.add(new Persona(256, "Mahélie", "Pentony", "odoo", 1, 46));
        lista.add(new Persona(257, "Dà", "Morris", "POO", 5, 22));
        lista.add(new Persona(258, "Dù", "Fice", "POO", 9, 70));
        lista.add(new Persona(259, "Cécilia", "Kiljan", "odoo", 5, 19));
        lista.add(new Persona(260, "Maïté", "Augur", "Patrones de diseño", 10, 33));
        lista.add(new Persona(261, "Léa", "Merrgan", "Patrones de diseño", 10, 45));
        lista.add(new Persona(262, "Märta", "Coupland", "BBDD", 3, 54));
        lista.add(new Persona(263, "Angèle", "Milier", "Angular", 7, 54));
        lista.add(new Persona(264, "Yóu", "Beynkn", "POO", 10, 22));
        lista.add(new Persona(265, "Marie-ève", "Kynett", "Oracle", 2, 37));
        lista.add(new Persona(266, "Angèle", "Berg", "NodeJs", 6, 27));
        lista.add(new Persona(267, "Annotés", "Swadlinge", "BBDD", 6, 41));
        lista.add(new Persona(268, "Marie-thérèse", "Irnis", "Java", 3, 63));
        lista.add(new Persona(269, "Béatrice", "Litherborough", "Express", 10, 31));
        lista.add(new Persona(270, "Gösta", "Delete", "PostgreSQL", 7, 27));
        lista.add(new Persona(271, "Angélique", "Hicken", "Acceso a datos", 3, 30));
        lista.add(new Persona(272, "Bérangère", "Brayn", "XML", 1, 71));
        lista.add(new Persona(273, "Kuí", "Laffin", "MySQL", 10, 64));
        lista.add(new Persona(274, "Eléonore", "Kenworthey", "odoo", 9, 63));
        lista.add(new Persona(275, "Anaé", "Olivella", "Patrones de diseño", 8, 37));
        lista.add(new Persona(276, "Edmée", "Doerffer", "NodeJs", 1, 56));
        lista.add(new Persona(277, "Edmée", "Riolfo", "MySQL", 10, 22));
        lista.add(new Persona(278, "Régine", "Gabbotts", "odoo", 10, 45));
        lista.add(new Persona(279, "Mélys", "Kleynermans", "Patrones de diseño", 10, 35));
        lista.add(new Persona(280, "Wá", "Matts", "Express", 6, 73));
        lista.add(new Persona(281, "Eléonore", "Quilligan", "Angular", 1, 50));
        lista.add(new Persona(282, "Marie-thérèse", "Dukes", "Patrones de diseño", 4, 20));
        lista.add(new Persona(283, "Danièle", "Girk", "NodeJs", 6, 44));
        lista.add(new Persona(284, "Josée", "Cantua", "NodeJs", 5, 60));
        lista.add(new Persona(285, "Eliès", "Vasiljevic", "odoo", 3, 62));
        lista.add(new Persona(286, "Marylène", "Burghall", "MySQL", 7, 69));
        lista.add(new Persona(287, "Solène", "Cultcheth", "BBDD", 6, 73));
        lista.add(new Persona(288, "Rébecca", "Ambrose", "PostgreSQL", 8, 21));
        lista.add(new Persona(289, "Pål", "Hutchins", "react", 5, 28));
        lista.add(new Persona(290, "Yáo", "Riha", "PostgreSQL", 9, 52));
        lista.add(new Persona(291, "Gwenaëlle", "Topp", "Java", 3, 36));
        lista.add(new Persona(292, "Loïca", "Granleese", "NodeJs", 8, 74));
        lista.add(new Persona(293, "Publicité", "Tripney", "NodeJs", 5, 40));
        lista.add(new Persona(294, "Pål", "Milbourne", "XML", 2, 60));
        lista.add(new Persona(295, "Cléa", "Martinho", "react", 7, 19));
        lista.add(new Persona(296, "Mén", "Neiland", "JavaScript", 1, 67));
        lista.add(new Persona(297, "Solène", "Bahl", "sql", 6, 49));
        lista.add(new Persona(298, "Mélinda", "Stansfield", "Java", 10, 67));
        lista.add(new Persona(299, "Bénédicte", "Granleese", "PostgreSQL", 3, 64));
        lista.add(new Persona(300, "Mårten", "Smales", "MySQL", 3, 34));
        lista.add(new Persona(301, "Marie-thérèse", "Margetts", "MySQL", 10, 20));
        lista.add(new Persona(302, "Lèi", "Schulkins", "sql", 7, 37));
        lista.add(new Persona(303, "Noëlla", "Astlatt", "react", 9, 20));
        lista.add(new Persona(304, "Bénédicte", "Race", "Java", 5, 62));
        lista.add(new Persona(305, "Maëline", "Natalie", "Java", 5, 70));
        lista.add(new Persona(306, "Kallisté", "Fandrich", "PostgreSQL", 5, 71));
        lista.add(new Persona(307, "Géraldine", "Prosh", "Express", 2, 35));
        lista.add(new Persona(308, "Maïlis", "Okker", "Patrones de diseño", 3, 45));
        lista.add(new Persona(309, "Pål", "Ezzle", "XML", 4, 29));
        lista.add(new Persona(310, "Mélodie", "Larvent", "NodeJs", 9, 35));
        lista.add(new Persona(311, "Maïlis", "Honnicott", "XML", 2, 49));
        lista.add(new Persona(312, "Maïlys", "MacTimpany", "Angular", 4, 46));
        lista.add(new Persona(313, "Alizée", "Pennicott", "Angular", 6, 21));
        lista.add(new Persona(314, "Andréanne", "Spybey", "Express", 3, 57));
        lista.add(new Persona(315, "Adélaïde", "Stichall", "react", 2, 44));
        lista.add(new Persona(316, "Aimée", "Cassie", "Oracle", 2, 37));
        lista.add(new Persona(317, "Inès", "Tear", "POO", 10, 50));
        lista.add(new Persona(318, "Léa", "Braganca", "Java", 6, 57));
        lista.add(new Persona(319, "Zhì", "Philliskirk", "react", 2, 66));
        lista.add(new Persona(320, "Edmée", "Asple", "PostgreSQL", 2, 27));
        lista.add(new Persona(321, "Marylène", "Millward", "XML", 8, 72));
        lista.add(new Persona(322, "Marie-ève", "Pinhorn", "Acceso a datos", 3, 50));
        lista.add(new Persona(323, "Maïté", "Dorwood", "Java", 2, 43));
        lista.add(new Persona(324, "Cléopatre", "Bichener", "Java", 8, 73));
        lista.add(new Persona(325, "Marlène", "Fealy", "react", 10, 52));
        lista.add(new Persona(326, "Célestine", "Staner", "Acceso a datos", 5, 44));
        lista.add(new Persona(327, "Publicité", "MacDonell", "sql", 7, 56));
        lista.add(new Persona(328, "Aimée", "Adelsberg", "sql", 1, 28));
        lista.add(new Persona(329, "Laïla", "Bufton", "Angular", 3, 38));
        lista.add(new Persona(330, "Géraldine", "Feather", "NodeJs", 10, 32));
        lista.add(new Persona(331, "Dorothée", "Buggs", "MySQL", 8, 70));
        lista.add(new Persona(332, "Mélanie", "Wane", "react", 9, 55));
        lista.add(new Persona(333, "Pò", "Arman", "BBDD", 9, 59));
        lista.add(new Persona(334, "Håkan", "Aspray", "MySQL", 9, 39));
        lista.add(new Persona(335, "Lucrèce", "Routh", "Express", 5, 18));
        lista.add(new Persona(336, "Solène", "Spirit", "Acceso a datos", 6, 18));
        lista.add(new Persona(337, "Ruì", "Khomin", "XML", 1, 34));
        lista.add(new Persona(338, "Yáo", "Uccello", "Acceso a datos", 1, 73));
        lista.add(new Persona(339, "Kuí", "While", "Oracle", 5, 37));
        lista.add(new Persona(340, "Bérénice", "Murthwaite", "NodeJs", 10, 20));
        lista.add(new Persona(341, "Åsa", "Dewerson", "sql", 6, 31));
        lista.add(new Persona(342, "Intéressant", "Fotheringham", "JavaScript", 4, 51));
        lista.add(new Persona(343, "Maëlann", "Jaycox", "Oracle", 5, 62));
        lista.add(new Persona(344, "Mén", "Denerley", "MySQL", 9, 24));
        lista.add(new Persona(345, "Mélia", "Lagden", "Express", 9, 23));
        lista.add(new Persona(346, "Laïla", "Bohden", "MySQL", 6, 55));
        lista.add(new Persona(347, "Esbjörn", "Canero", "Oracle", 1, 44));
        lista.add(new Persona(348, "Judicaël", "Matignon", "odoo", 2, 44));
        lista.add(new Persona(349, "Célestine", "Cully", "PostgreSQL", 9, 66));
        lista.add(new Persona(350, "Léonie", "Caramuscia", "odoo", 4, 33));
        lista.add(new Persona(351, "Cécile", "Pentercost", "POO", 4, 41));
        lista.add(new Persona(352, "Hélèna", "Wooland", "odoo", 10, 24));
        lista.add(new Persona(353, "Jú", "Brodeau", "NodeJs", 2, 25));
        lista.add(new Persona(354, "Intéressant", "Fraczkiewicz", "sql", 9, 69));
        lista.add(new Persona(355, "Zhì", "Degg", "sql", 6, 32));
        lista.add(new Persona(356, "Liè", "Diglin", "Oracle", 6, 36));
        lista.add(new Persona(357, "Marylène", "Nuttey", "Java", 3, 70));
        lista.add(new Persona(358, "Görel", "Priestley", "MySQL", 3, 44));
        lista.add(new Persona(359, "Kévina", "Kristoffersson", "Oracle", 8, 18));
        lista.add(new Persona(360, "Håkan", "McCleary", "POO", 8, 46));
        lista.add(new Persona(361, "Loïc", "Maxworthy", "XML", 1, 45));
        lista.add(new Persona(362, "Amélie", "Bircher", "Express", 7, 27));
        lista.add(new Persona(363, "Liè", "Myford", "sql", 7, 32));
        lista.add(new Persona(364, "Eléa", "Hiscocks", "Express", 3, 31));
        lista.add(new Persona(365, "Océane", "Pelz", "BBDD", 6, 75));
        lista.add(new Persona(366, "Almérinda", "Darby", "Java", 6, 74));
        lista.add(new Persona(367, "Alizée", "Olner", "sql", 4, 72));
        lista.add(new Persona(368, "Desirée", "Dolby", "MySQL", 8, 31));
        lista.add(new Persona(369, "Nuó", "Augur", "Express", 9, 20));
        lista.add(new Persona(370, "Kuí", "Wandrey", "NodeJs", 10, 29));
        lista.add(new Persona(371, "Maëly", "Sheaber", "odoo", 7, 67));
        lista.add(new Persona(372, "Edmée", "Hitzschke", "BBDD", 5, 38));
        lista.add(new Persona(373, "Vérane", "O' Cuolahan", "PostgreSQL", 5, 50));
        lista.add(new Persona(374, "Lóng", "Scampion", "sql", 8, 32));
        lista.add(new Persona(375, "Adélaïde", "Newcomb", "sql", 5, 35));
        lista.add(new Persona(376, "Lyséa", "Aldwich", "JavaScript", 3, 20));
        lista.add(new Persona(377, "Esbjörn", "Cotter", "Acceso a datos", 3, 57));
        lista.add(new Persona(378, "Océanne", "Cheesley", "Oracle", 7, 32));
        lista.add(new Persona(379, "Vérane", "Inseal", "BBDD", 4, 54));
        lista.add(new Persona(380, "Maëlle", "Smithen", "JavaScript", 3, 37));
        lista.add(new Persona(381, "Edmée", "Fiddy", "Acceso a datos", 10, 22));
        lista.add(new Persona(382, "Aí", "Goodanew", "NodeJs", 8, 67));
        lista.add(new Persona(383, "Cécilia", "Piggins", "XML", 8, 57));
        lista.add(new Persona(384, "Marie-hélène", "Winslow", "JavaScript", 2, 46));
        lista.add(new Persona(385, "Personnalisée", "Pluthero", "Acceso a datos", 4, 34));
        lista.add(new Persona(386, "Cloé", "Firbank", "POO", 7, 35));
        lista.add(new Persona(387, "Magdalène", "Ricardet", "POO", 3, 69));
        lista.add(new Persona(388, "Danièle", "Glassford", "MySQL", 9, 40));
        lista.add(new Persona(389, "Edmée", "Limon", "NodeJs", 10, 18));
        lista.add(new Persona(390, "Naéva", "Boles", "BBDD", 1, 39));
        lista.add(new Persona(391, "Léandre", "Dayment", "Patrones de diseño", 5, 20));
        lista.add(new Persona(392, "Laurène", "Sealove", "NodeJs", 10, 52));
        lista.add(new Persona(393, "Thérèsa", "Picopp", "Java", 5, 24));
        lista.add(new Persona(394, "Maïlys", "Dykas", "Oracle", 2, 21));
        lista.add(new Persona(395, "Annotés", "Gillooly", "Express", 8, 57));
        lista.add(new Persona(396, "Mélodie", "Jaime", "BBDD", 5, 22));
        lista.add(new Persona(397, "Mélissandre", "Beet", "odoo", 7, 24));
        lista.add(new Persona(398, "Maëly", "Stonebanks", "Oracle", 5, 57));
        lista.add(new Persona(399, "Véronique", "Mulderrig", "PostgreSQL", 1, 29));
        lista.add(new Persona(400, "Cécile", "Brodie", "MySQL", 2, 22));
        lista.add(new Persona(401, "Stéphanie", "Clare", "Angular", 8, 60));
        lista.add(new Persona(402, "Méghane", "Carn", "sql", 1, 34));
        lista.add(new Persona(403, "Anaël", "Calvert", "sql", 6, 43));
        lista.add(new Persona(404, "Bérengère", "Castello", "NodeJs", 10, 43));
        lista.add(new Persona(405, "Nélie", "Prando", "PostgreSQL", 5, 46));
        lista.add(new Persona(406, "Märta", "Maltster", "odoo", 4, 22));
        lista.add(new Persona(407, "Fèi", "Bader", "JavaScript", 5, 29));
        lista.add(new Persona(408, "Loïs", "Canfer", "PostgreSQL", 10, 60));
        lista.add(new Persona(409, "Laïla", "Darwen", "PostgreSQL", 1, 72));
        lista.add(new Persona(410, "Personnalisée", "Cooley", "Angular", 3, 63));
        lista.add(new Persona(411, "Clélia", "Pyett", "Express", 7, 69));
        lista.add(new Persona(412, "Thérèse", "Shercliff", "POO", 2, 73));
        lista.add(new Persona(413, "Eugénie", "Creser", "MySQL", 1, 27));
        lista.add(new Persona(414, "Naëlle", "Whybrow", "sql", 5, 47));
        lista.add(new Persona(415, "Maëlann", "Andrassy", "Patrones de diseño", 8, 29));
        lista.add(new Persona(416, "Régine", "Tym", "Java", 9, 48));
        lista.add(new Persona(417, "Personnalisée", "Rooze", "PostgreSQL", 7, 45));
        lista.add(new Persona(418, "Méghane", "Goter", "Java", 5, 53));
        lista.add(new Persona(419, "Marie-noël", "Spillane", "BBDD", 6, 69));
        lista.add(new Persona(420, "Béatrice", "Cutmore", "MySQL", 2, 38));
        lista.add(new Persona(421, "Eliès", "Baitman", "JavaScript", 3, 69));
        lista.add(new Persona(422, "Aimée", "Hitscher", "odoo", 10, 22));
        lista.add(new Persona(423, "Maïlis", "Scawn", "Oracle", 5, 49));
        lista.add(new Persona(424, "Marie-hélène", "Krzysztof", "POO", 2, 43));
        lista.add(new Persona(425, "Yénora", "Stoving", "Java", 3, 41));
        lista.add(new Persona(426, "Médiamass", "Gerrill", "Angular", 3, 73));
        lista.add(new Persona(427, "Cléa", "Vittery", "NodeJs", 1, 32));
        lista.add(new Persona(428, "Marie-thérèse", "de Villier", "odoo", 4, 40));
        lista.add(new Persona(429, "Félicie", "Sutheran", "BBDD", 6, 28));
        lista.add(new Persona(430, "Wá", "Kornacki", "POO", 8, 72));
        lista.add(new Persona(431, "Nélie", "Edwick", "POO", 1, 68));
        lista.add(new Persona(432, "Eléonore", "Coode", "MySQL", 4, 39));
        lista.add(new Persona(433, "Miléna", "Gowdridge", "react", 5, 29));
        lista.add(new Persona(434, "Adèle", "Ecclestone", "POO", 6, 62));
        lista.add(new Persona(435, "Lyséa", "Eric", "MySQL", 2, 29));
        lista.add(new Persona(436, "Marie-noël", "Ridett", "Express", 6, 43));
        lista.add(new Persona(437, "Torbjörn", "Cheer", "BBDD", 9, 41));
        lista.add(new Persona(438, "Naëlle", "Gummow", "Java", 3, 38));
        lista.add(new Persona(439, "Méghane", "Impett", "PostgreSQL", 10, 27));
        lista.add(new Persona(440, "Zhì", "Stedell", "MySQL", 4, 53));
        lista.add(new Persona(441, "Léandre", "Dougan", "Java", 10, 45));
        lista.add(new Persona(442, "Stéphanie", "Bingall", "react", 9, 51));
        lista.add(new Persona(443, "Marie-ève", "Danzelman", "Angular", 1, 57));
        lista.add(new Persona(444, "Frédérique", "Whale", "Oracle", 5, 30));
        lista.add(new Persona(445, "Anaël", "Rusk", "NodeJs", 8, 73));
        lista.add(new Persona(446, "Mélys", "Henzer", "POO", 5, 54));
        lista.add(new Persona(447, "Valérie", "Roderighi", "odoo", 7, 49));
        lista.add(new Persona(448, "Märta", "Masdon", "Oracle", 6, 26));
        lista.add(new Persona(449, "Lauréna", "Tregea", "POO", 10, 41));
        lista.add(new Persona(450, "Maëlla", "Chitham", "NodeJs", 8, 25));
        lista.add(new Persona(451, "Zhì", "Borgesio", "PostgreSQL", 6, 75));
        lista.add(new Persona(452, "Camélia", "Mattaus", "Angular", 9, 32));
        lista.add(new Persona(453, "Åsa", "Oby", "Patrones de diseño", 5, 25));
        lista.add(new Persona(454, "Cléa", "Flacknoe", "MySQL", 6, 47));
        lista.add(new Persona(455, "Frédérique", "Ife", "Express", 10, 43));
        lista.add(new Persona(456, "Edmée", "Bardey", "Angular", 9, 64));
        lista.add(new Persona(457, "Görel", "Talloe", "PostgreSQL", 10, 64));
        lista.add(new Persona(458, "Léana", "Alphonso", "PostgreSQL", 9, 36));
        lista.add(new Persona(459, "Anaé", "Aymerich", "Express", 9, 51));
        lista.add(new Persona(460, "Athéna", "Emerine", "react", 4, 21));
        lista.add(new Persona(461, "Erwéi", "Deverell", "Oracle", 7, 35));
        lista.add(new Persona(462, "Michèle", "Colles", "XML", 1, 46));
        lista.add(new Persona(463, "Anaëlle", "Blackaller", "react", 4, 70));
        lista.add(new Persona(464, "Bécassine", "Rodden", "MySQL", 2, 61));
        lista.add(new Persona(465, "Åke", "Ralls", "odoo", 9, 51));
        lista.add(new Persona(466, "Loïc", "Withull", "odoo", 2, 29));
        lista.add(new Persona(467, "Rachèle", "Garnsey", "PostgreSQL", 1, 57));
        lista.add(new Persona(468, "Bécassine", "Folbige", "Angular", 2, 59));
        lista.add(new Persona(469, "Maëlla", "Genge", "XML", 4, 50));
        lista.add(new Persona(470, "Cloé", "Gaudin", "Angular", 7, 47));
        lista.add(new Persona(471, "Bénédicte", "McGhie", "Angular", 9, 65));
        lista.add(new Persona(472, "Mahélie", "Brockway", "Java", 5, 38));
        lista.add(new Persona(473, "Publicité", "Weatherup", "odoo", 9, 41));
        lista.add(new Persona(474, "Yóu", "Hardistry", "Oracle", 6, 42));
        lista.add(new Persona(475, "Naëlle", "Tolomei", "XML", 9, 74));
        lista.add(new Persona(476, "Maïté", "Klarzynski", "Express", 2, 49));
        lista.add(new Persona(477, "Naéva", "Smales", "Java", 4, 69));
        lista.add(new Persona(478, "Bérénice", "Brodway", "react", 10, 61));
        lista.add(new Persona(479, "Sòng", "Coggell", "POO", 6, 65));
        lista.add(new Persona(480, "Sòng", "Robertz", "Express", 6, 37));
        lista.add(new Persona(481, "Yóu", "Arber", "Acceso a datos", 2, 42));
        lista.add(new Persona(482, "Wá", "Dignall", "Java", 7, 60));
        lista.add(new Persona(483, "Chloé", "Renoden", "MySQL", 8, 71));
        lista.add(new Persona(484, "Lài", "Olyfant", "Oracle", 4, 73));
        lista.add(new Persona(485, "Märta", "Emblem", "Acceso a datos", 6, 38));
        lista.add(new Persona(486, "Tú", "Pinfold", "Patrones de diseño", 3, 64));
        lista.add(new Persona(487, "Almérinda", "Veare", "PostgreSQL", 3, 71));
        lista.add(new Persona(488, "Mà", "Linwood", "react", 2, 35));
        lista.add(new Persona(489, "Torbjörn", "Denziloe", "sql", 2, 72));
        lista.add(new Persona(490, "Léa", "Currum", "XML", 2, 75));
        lista.add(new Persona(491, "Loïs", "Ivanenkov", "BBDD", 10, 18));
        lista.add(new Persona(492, "Eloïse", "Astley", "Express", 10, 19));
        lista.add(new Persona(493, "Liè", "Thoday", "Angular", 5, 47));
        lista.add(new Persona(494, "Gwenaëlle", "Zecchii", "Java", 1, 75));
        lista.add(new Persona(495, "Annotés", "Beddie", "POO", 5, 36));
        lista.add(new Persona(496, "Illustrée", "Vannuccini", "JavaScript", 7, 24));
        lista.add(new Persona(497, "Marylène", "Flintoft", "sql", 1, 60));
        lista.add(new Persona(498, "Illustrée", "Boddam", "XML", 6, 21));
        lista.add(new Persona(499, "Intéressant", "Alders", "react", 4, 29));
        lista.add(new Persona(500, "Örjan", "Pitcaithly", "Acceso a datos", 8, 57));
        lista.add(new Persona(501, "Naéva", "Fulep", "BBDD", 6, 25));
        lista.add(new Persona(502, "Alizée", "Burston", "PostgreSQL", 8, 22));
        lista.add(new Persona(503, "Uò", "Binham", "XML", 6, 44));
        lista.add(new Persona(504, "Anaé", "Southern", "react", 4, 32));
        lista.add(new Persona(505, "Noëlla", "Camois", "Patrones de diseño", 5, 65));
        lista.add(new Persona(506, "Publicité", "Ewols", "NodeJs", 2, 71));
        lista.add(new Persona(507, "Maïwenn", "Snipe", "NodeJs", 9, 63));
        lista.add(new Persona(508, "Táng", "Joost", "NodeJs", 6, 22));
        lista.add(new Persona(509, "Dafnée", "Leinthall", "BBDD", 5, 66));
        lista.add(new Persona(510, "Marie-noël", "Hardy", "Angular", 1, 32));
        lista.add(new Persona(511, "Maïlis", "Thomke", "react", 9, 21));
        lista.add(new Persona(512, "Stévina", "Martinelli", "JavaScript", 1, 36));
        lista.add(new Persona(513, "Styrbjörn", "Dormer", "sql", 4, 60));
        lista.add(new Persona(514, "Marie-thérèse", "Maddy", "XML", 7, 48));
        lista.add(new Persona(515, "Néhémie", "Dyter", "PostgreSQL", 7, 52));
        lista.add(new Persona(516, "Maï", "Larham", "Express", 9, 58));
        lista.add(new Persona(517, "Mà", "Livzey", "Oracle", 8, 28));
        lista.add(new Persona(518, "Stévina", "Phillot", "odoo", 1, 61));
        lista.add(new Persona(519, "Daphnée", "Caseley", "odoo", 7, 62));
        lista.add(new Persona(520, "Mårten", "Simes", "sql", 9, 33));
        lista.add(new Persona(521, "Marie-josée", "Le Estut", "Patrones de diseño", 5, 63));
        lista.add(new Persona(522, "Märta", "Caltun", "POO", 8, 51));
        lista.add(new Persona(523, "Pélagie", "Hawthorn", "Express", 1, 53));
        lista.add(new Persona(524, "Laïla", "Zanre", "XML", 6, 47));
        lista.add(new Persona(525, "Lorène", "Vondra", "MySQL", 6, 68));
        lista.add(new Persona(526, "Jú", "Frigot", "Angular", 2, 28));
        lista.add(new Persona(527, "Laïla", "Siebert", "PostgreSQL", 10, 57));
        lista.add(new Persona(528, "Dafnée", "Allett", "Angular", 6, 66));
        lista.add(new Persona(529, "Mélys", "Counsell", "XML", 2, 65));
        lista.add(new Persona(530, "Jú", "Pecht", "Express", 2, 39));
        lista.add(new Persona(531, "Athéna", "Bamford", "Patrones de diseño", 4, 59));
        lista.add(new Persona(532, "Publicité", "Scamadin", "JavaScript", 6, 26));
        lista.add(new Persona(533, "Adélaïde", "Challis", "XML", 1, 35));
        lista.add(new Persona(534, "Agnès", "Ozintsev", "sql", 5, 36));
        lista.add(new Persona(535, "Mélanie", "Thorrold", "POO", 1, 63));
        lista.add(new Persona(536, "Joséphine", "Moorcraft", "Java", 5, 68));
        lista.add(new Persona(537, "Laïla", "Wrigley", "JavaScript", 4, 51));
        lista.add(new Persona(538, "Miléna", "Aiton", "Patrones de diseño", 3, 34));
        lista.add(new Persona(539, "Maïté", "Hurne", "BBDD", 2, 57));
        lista.add(new Persona(540, "Léonie", "Gillmore", "NodeJs", 5, 57));
        lista.add(new Persona(541, "Andréa", "Bondar", "odoo", 3, 48));
        lista.add(new Persona(542, "Táng", "Wippermann", "Patrones de diseño", 9, 57));
        lista.add(new Persona(543, "Athéna", "Peevor", "sql", 2, 39));
        lista.add(new Persona(544, "Anaël", "Scallon", "Java", 6, 56));
        lista.add(new Persona(545, "Sélène", "Tallet", "MySQL", 5, 52));
        lista.add(new Persona(546, "Mà", "Rummer", "Patrones de diseño", 6, 37));
        lista.add(new Persona(547, "Almérinda", "Kline", "react", 8, 32));
        lista.add(new Persona(548, "Görel", "Syne", "POO", 10, 33));
        lista.add(new Persona(549, "Agnès", "Jendrach", "NodeJs", 9, 58));
        lista.add(new Persona(550, "Estée", "Moffett", "NodeJs", 1, 59));
        lista.add(new Persona(551, "Maëlys", "Liles", "POO", 2, 68));
        lista.add(new Persona(552, "Torbjörn", "Mains", "Oracle", 4, 34));
        lista.add(new Persona(553, "Léonie", "Jedrychowski", "Acceso a datos", 4, 24));
        lista.add(new Persona(554, "Esbjörn", "Skentelbery", "Angular", 2, 39));
        lista.add(new Persona(555, "Céline", "Ghiotto", "NodeJs", 3, 52));
        lista.add(new Persona(556, "Marie-hélène", "Broddle", "Java", 5, 74));
        lista.add(new Persona(557, "Loïs", "Cubberley", "POO", 3, 37));
        lista.add(new Persona(558, "Mélinda", "Tregidga", "Oracle", 3, 19));
        lista.add(new Persona(559, "Dà", "Sharply", "XML", 9, 18));
        lista.add(new Persona(560, "Léandre", "Hehl", "JavaScript", 6, 23));
        lista.add(new Persona(561, "Eléonore", "McPhate", "XML", 5, 75));
        lista.add(new Persona(562, "Sélène", "Morgon", "XML", 7, 55));
        lista.add(new Persona(563, "Mégane", "Braidon", "Java", 9, 61));
        lista.add(new Persona(564, "Annotée", "Creyke", "POO", 5, 40));
        lista.add(new Persona(565, "Véronique", "Pettis", "POO", 10, 40));
        lista.add(new Persona(566, "Inès", "Plaunch", "BBDD", 4, 23));
        lista.add(new Persona(567, "Mahélie", "Dumbreck", "NodeJs", 2, 69));
        lista.add(new Persona(568, "Liè", "Kerfut", "odoo", 9, 62));
        lista.add(new Persona(569, "Adélaïde", "Pemberton", "NodeJs", 8, 65));
        lista.add(new Persona(570, "Tú", "Seywood", "NodeJs", 8, 19));
        lista.add(new Persona(571, "Mylène", "Hallock", "Acceso a datos", 5, 61));
        lista.add(new Persona(572, "Athéna", "Gladtbach", "NodeJs", 1, 50));
        lista.add(new Persona(573, "Joséphine", "Weal", "NodeJs", 1, 65));
        lista.add(new Persona(574, "Lèi", "Deem", "MySQL", 2, 68));
        lista.add(new Persona(575, "Thérèse", "Stenet", "odoo", 5, 50));
        lista.add(new Persona(576, "Maëline", "Kalaher", "PostgreSQL", 7, 59));
        lista.add(new Persona(577, "Stéphanie", "Wrinch", "Acceso a datos", 8, 24));
        lista.add(new Persona(578, "Andréanne", "Liddon", "Express", 1, 49));
        lista.add(new Persona(579, "Håkan", "Iacobetto", "PostgreSQL", 6, 65));
        lista.add(new Persona(580, "Bérénice", "Wingate", "POO", 10, 73));
        lista.add(new Persona(581, "Pénélope", "Bougourd", "PostgreSQL", 8, 62));
        lista.add(new Persona(582, "Mégane", "Broske", "MySQL", 3, 37));
        lista.add(new Persona(583, "Léana", "Kinney", "Angular", 7, 22));
        lista.add(new Persona(584, "Régine", "Portman", "BBDD", 7, 33));
        lista.add(new Persona(585, "Intéressant", "Stiffkins", "NodeJs", 1, 35));
        lista.add(new Persona(586, "Publicité", "Emerton", "NodeJs", 5, 55));
        lista.add(new Persona(587, "Noémie", "Elven", "BBDD", 8, 52));
        lista.add(new Persona(588, "Desirée", "Laugherane", "PostgreSQL", 3, 61));
        lista.add(new Persona(589, "Maï", "Connichie", "BBDD", 6, 41));
        lista.add(new Persona(590, "Mélinda", "Fausset", "Acceso a datos", 9, 53));
        lista.add(new Persona(591, "Michèle", "Voase", "sql", 6, 53));
        lista.add(new Persona(592, "Yénora", "Gillman", "XML", 8, 54));
        lista.add(new Persona(593, "Alizée", "Stiegar", "Acceso a datos", 9, 31));
        lista.add(new Persona(594, "Véronique", "Cottage", "odoo", 5, 37));
        lista.add(new Persona(595, "Marie-josée", "Giles", "POO", 5, 46));
        lista.add(new Persona(596, "Clémence", "Beckensall", "BBDD", 8, 30));
        lista.add(new Persona(597, "Adélaïde", "Learoid", "Patrones de diseño", 4, 45));
        lista.add(new Persona(598, "Lài", "Daye", "MySQL", 2, 51));
        lista.add(new Persona(599, "Aimée", "Borrell", "XML", 8, 58));
        lista.add(new Persona(600, "Publicité", "Gumb", "MySQL", 10, 45));
        lista.add(new Persona(601, "Simplifiés", "Elcome", "react", 7, 48));
        lista.add(new Persona(602, "André", "Corking", "PostgreSQL", 4, 44));
        lista.add(new Persona(603, "Lucrèce", "Curnokk", "JavaScript", 2, 69));
        lista.add(new Persona(604, "Véronique", "Emby", "Patrones de diseño", 7, 45));
        lista.add(new Persona(605, "Méghane", "Balm", "Express", 2, 42));
        lista.add(new Persona(606, "Geneviève", "Boustead", "BBDD", 5, 70));
        lista.add(new Persona(607, "Ruò", "Laphorn", "PostgreSQL", 2, 25));
        lista.add(new Persona(608, "Thérèsa", "Slessor", "Acceso a datos", 2, 57));
        lista.add(new Persona(609, "Lèi", "Wellstood", "Oracle", 8, 75));
        lista.add(new Persona(610, "Maïlys", "Faughny", "Patrones de diseño", 4, 35));
        lista.add(new Persona(611, "Régine", "Mathews", "react", 9, 68));
        lista.add(new Persona(612, "Vérane", "Kulis", "odoo", 9, 29));
        lista.add(new Persona(613, "Lèi", "Swinley", "JavaScript", 5, 74));
        lista.add(new Persona(614, "Zoé", "De Roos", "Java", 1, 31));
        lista.add(new Persona(615, "Zoé", "Hulstrom", "Java", 6, 40));
        lista.add(new Persona(616, "Lèi", "Chartres", "react", 1, 68));
        lista.add(new Persona(617, "Célestine", "Haselgrove", "Express", 2, 29));
        lista.add(new Persona(618, "Laïla", "Wrench", "Java", 9, 25));
        lista.add(new Persona(619, "Méryl", "MacLure", "Patrones de diseño", 9, 42));
        lista.add(new Persona(620, "Régine", "Mottley", "Express", 10, 52));
        lista.add(new Persona(621, "Görel", "Youthed", "MySQL", 4, 47));
        lista.add(new Persona(622, "Clémence", "Donisthorpe", "JavaScript", 9, 64));
        lista.add(new Persona(623, "Faîtes", "Cansdill", "POO", 1, 38));
        lista.add(new Persona(624, "Bérengère", "Le Barr", "Java", 9, 59));
        lista.add(new Persona(625, "Léone", "Yankin", "Oracle", 4, 50));
        lista.add(new Persona(626, "Stéphanie", "Master", "Acceso a datos", 6, 27));
        lista.add(new Persona(627, "Marlène", "Wasmuth", "Acceso a datos", 5, 51));
        lista.add(new Persona(628, "Lèi", "Sole", "Angular", 5, 36));
        lista.add(new Persona(629, "Athéna", "Marle", "XML", 4, 28));
        lista.add(new Persona(630, "Anaëlle", "Northgraves", "Java", 3, 37));
        lista.add(new Persona(631, "Björn", "Kurdani", "Oracle", 8, 52));
        lista.add(new Persona(632, "Marie-hélène", "Chillcot", "react", 5, 22));
        lista.add(new Persona(633, "Maëly", "Jeste", "sql", 6, 70));
        lista.add(new Persona(634, "Annotés", "Winfindale", "odoo", 9, 36));
        lista.add(new Persona(635, "Kévina", "Viollet", "BBDD", 10, 45));
        lista.add(new Persona(636, "Maëlys", "Jobbing", "odoo", 10, 46));
        lista.add(new Persona(637, "Léa", "Daid", "Oracle", 4, 21));
        lista.add(new Persona(638, "Annotée", "Macieja", "NodeJs", 7, 33));
        lista.add(new Persona(639, "Wá", "Puddefoot", "Acceso a datos", 5, 32));
        lista.add(new Persona(640, "Vérane", "Brugh", "BBDD", 5, 31));
        lista.add(new Persona(641, "Méng", "Riccio", "NodeJs", 6, 68));
        lista.add(new Persona(642, "Hélène", "Edmonstone", "POO", 3, 52));
        lista.add(new Persona(643, "Mélodie", "Arnolds", "NodeJs", 7, 75));
        lista.add(new Persona(644, "Maïlys", "Simonin", "react", 10, 37));
        lista.add(new Persona(645, "Hélèna", "Vel", "Angular", 3, 67));
        lista.add(new Persona(646, "Cléopatre", "Grantham", "Acceso a datos", 3, 52));
        lista.add(new Persona(647, "Gösta", "Tayler", "Angular", 6, 71));
        lista.add(new Persona(648, "Eliès", "Mathissen", "BBDD", 6, 39));
        lista.add(new Persona(649, "Océanne", "McEnhill", "Oracle", 4, 70));
        lista.add(new Persona(650, "Ruì", "Imison", "XML", 1, 33));
        lista.add(new Persona(651, "Wá", "Ladewig", "odoo", 4, 48));
        lista.add(new Persona(652, "Edmée", "Skyner", "MySQL", 3, 53));
        lista.add(new Persona(653, "Bénédicte", "Hadden", "Patrones de diseño", 4, 54));
        lista.add(new Persona(654, "Mélys", "Plummer", "odoo", 8, 56));
        lista.add(new Persona(655, "Léandre", "Keyser", "JavaScript", 3, 27));
        lista.add(new Persona(656, "Lauréna", "Tromans", "BBDD", 9, 18));
        lista.add(new Persona(657, "Cécilia", "Gillivrie", "XML", 5, 38));
        lista.add(new Persona(658, "Clémentine", "Sheaf", "NodeJs", 5, 60));
        lista.add(new Persona(659, "Léone", "Dorsey", "react", 2, 67));
        lista.add(new Persona(660, "Lèi", "Strathern", "sql", 7, 63));
        lista.add(new Persona(661, "Lèi", "Cecchi", "Express", 3, 67));
        lista.add(new Persona(662, "Ráo", "Luety", "Patrones de diseño", 3, 22));
        lista.add(new Persona(663, "Chloé", "Kennett", "Angular", 2, 21));
        lista.add(new Persona(664, "Lài", "Wand", "Express", 6, 69));
        lista.add(new Persona(665, "Lóng", "Frarey", "JavaScript", 6, 45));
        lista.add(new Persona(666, "Anaé", "Yendle", "JavaScript", 7, 53));
        lista.add(new Persona(667, "Océanne", "Stoney", "Acceso a datos", 10, 74));
        lista.add(new Persona(668, "Mà", "Wood", "MySQL", 4, 75));
        lista.add(new Persona(669, "Méline", "Scane", "odoo", 9, 60));
        lista.add(new Persona(670, "Yú", "Malins", "POO", 1, 66));
        lista.add(new Persona(671, "Véronique", "Fairhead", "Angular", 4, 68));
        lista.add(new Persona(672, "Réservés", "Lammiman", "BBDD", 5, 46));
        lista.add(new Persona(673, "Tán", "Barsby", "JavaScript", 6, 21));
        lista.add(new Persona(674, "Mårten", "Sanzio", "Angular", 6, 57));
        lista.add(new Persona(675, "Bérengère", "Greenough", "XML", 10, 40));
        lista.add(new Persona(676, "Cléopatre", "Huddart", "sql", 9, 25));
        lista.add(new Persona(677, "Camélia", "Davers", "Express", 8, 57));
        lista.add(new Persona(678, "Mélanie", "Prover", "JavaScript", 4, 75));
        lista.add(new Persona(679, "Crééz", "Hanretty", "odoo", 6, 75));
        lista.add(new Persona(680, "Camélia", "Rebert", "sql", 7, 55));
        lista.add(new Persona(681, "Pò", "Lapere", "Angular", 3, 39));
        lista.add(new Persona(682, "Maïwenn", "Woodes", "Oracle", 3, 26));
        lista.add(new Persona(683, "Cinéma", "McAuslene", "Java", 1, 24));
        lista.add(new Persona(684, "Amélie", "Safell", "PostgreSQL", 7, 60));
        lista.add(new Persona(685, "Réservés", "Dukesbury", "PostgreSQL", 8, 55));
        lista.add(new Persona(686, "Anaël", "Belvin", "MySQL", 6, 31));
        lista.add(new Persona(687, "Cléopatre", "MacRirie", "PostgreSQL", 6, 25));
        lista.add(new Persona(688, "Pélagie", "Bolitho", "XML", 2, 59));
        lista.add(new Persona(689, "Médiamass", "Jura", "Java", 10, 65));
        lista.add(new Persona(690, "Andrée", "Bettaney", "sql", 3, 25));
        lista.add(new Persona(691, "Fèi", "Veasey", "Angular", 2, 75));
        lista.add(new Persona(692, "Mélina", "Carus", "NodeJs", 6, 58));
        lista.add(new Persona(693, "Aloïs", "Ingerson", "odoo", 9, 34));
        lista.add(new Persona(694, "Clémence", "Cherm", "PostgreSQL", 10, 30));
        lista.add(new Persona(695, "Gisèle", "Ripley", "Oracle", 1, 70));
        lista.add(new Persona(696, "Maëline", "Shier", "Java", 1, 67));
        lista.add(new Persona(697, "Naëlle", "Block", "NodeJs", 5, 40));
        lista.add(new Persona(698, "Médiamass", "Westmancoat", "XML", 2, 73));
        lista.add(new Persona(699, "Gérald", "Gobeau", "Express", 4, 71));
        lista.add(new Persona(700, "Andréanne", "Mayho", "XML", 4, 38));
        lista.add(new Persona(701, "Björn", "Ronca", "MySQL", 7, 40));
        lista.add(new Persona(702, "Maïly", "Maudson", "Express", 2, 30));
        lista.add(new Persona(703, "Märta", "Tolomelli", "Java", 8, 20));
        lista.add(new Persona(704, "Laurélie", "Charity", "JavaScript", 5, 26));
        lista.add(new Persona(705, "Andrée", "Ritmeier", "POO", 3, 66));
        lista.add(new Persona(706, "Gaëlle", "Essam", "NodeJs", 10, 31));
        lista.add(new Persona(707, "Mélina", "Crummay", "JavaScript", 2, 54));
        lista.add(new Persona(708, "Cécilia", "O'Coskerry", "XML", 7, 59));
        lista.add(new Persona(709, "Alizée", "Simonsson", "odoo", 4, 72));
        lista.add(new Persona(710, "Maëly", "Jemison", "Angular", 4, 75));
        lista.add(new Persona(711, "Ruò", "Iacovucci", "sql", 9, 75));
        lista.add(new Persona(712, "Yáo", "Kernocke", "Express", 4, 36));
        lista.add(new Persona(713, "Mélys", "Verling", "react", 1, 53));
        lista.add(new Persona(714, "Inès", "Budden", "BBDD", 7, 74));
        lista.add(new Persona(715, "Åsa", "Revie", "Oracle", 8, 63));
        lista.add(new Persona(716, "Naëlle", "Rigbye", "Java", 2, 39));
        lista.add(new Persona(717, "Stévina", "Cawthorn", "POO", 6, 33));
        lista.add(new Persona(718, "Yè", "Paxforde", "Express", 8, 20));
        lista.add(new Persona(719, "Marlène", "McCahey", "sql", 7, 64));
        lista.add(new Persona(720, "Méline", "Stimson", "odoo", 8, 37));
        lista.add(new Persona(721, "Noëlla", "Alten", "Angular", 1, 21));
        lista.add(new Persona(722, "Réjane", "Gianninotti", "odoo", 10, 55));
        lista.add(new Persona(723, "Hélène", "Chastang", "Patrones de diseño", 8, 47));
        lista.add(new Persona(724, "Kuí", "Bransgrove", "NodeJs", 2, 37));
        lista.add(new Persona(725, "Dà", "Archdeckne", "XML", 4, 23));
        lista.add(new Persona(726, "Nadège", "Kerbler", "react", 10, 65));
        lista.add(new Persona(727, "Crééz", "Bowshire", "PostgreSQL", 2, 59));
        lista.add(new Persona(728, "Maï", "Barker", "Acceso a datos", 5, 48));
        lista.add(new Persona(729, "Anaël", "MacLachlan", "BBDD", 4, 35));
        lista.add(new Persona(730, "Göran", "Legen", "Java", 9, 58));
        lista.add(new Persona(731, "Bérangère", "Garatty", "JavaScript", 9, 72));
        lista.add(new Persona(732, "Mårten", "Baxill", "sql", 2, 39));
        lista.add(new Persona(733, "Léa", "Dartnall", "Express", 7, 64));
        lista.add(new Persona(734, "Eléonore", "Pratley", "sql", 7, 62));
        lista.add(new Persona(735, "Kù", "Vise", "odoo", 10, 38));
        lista.add(new Persona(736, "Mylène", "Fancott", "Patrones de diseño", 4, 31));
        lista.add(new Persona(737, "Méryl", "Perrie", "Express", 4, 42));
        lista.add(new Persona(738, "Göran", "Mailes", "Oracle", 6, 24));
        lista.add(new Persona(739, "Mélia", "Mountcastle", "BBDD", 10, 51));
        lista.add(new Persona(740, "Göran", "Airs", "Angular", 8, 22));
        lista.add(new Persona(741, "Léandre", "Lealle", "Patrones de diseño", 9, 39));
        lista.add(new Persona(742, "Nélie", "Liccardo", "Java", 8, 48));
        lista.add(new Persona(743, "Noémie", "Smythe", "NodeJs", 5, 71));
        lista.add(new Persona(744, "Yú", "Stonnell", "NodeJs", 6, 65));
        lista.add(new Persona(745, "Publicité", "Gencke", "MySQL", 9, 27));
        lista.add(new Persona(746, "Lài", "Cottle", "sql", 4, 43));
        lista.add(new Persona(747, "Séverine", "Hazzard", "Oracle", 9, 74));
        lista.add(new Persona(748, "Adélaïde", "Morais", "XML", 4, 73));
        lista.add(new Persona(749, "Séverine", "Purches", "POO", 9, 34));
        lista.add(new Persona(750, "Noémie", "McMeeking", "BBDD", 2, 51));
        lista.add(new Persona(751, "Nélie", "Raspel", "NodeJs", 3, 20));
        lista.add(new Persona(752, "Edmée", "Busch", "Oracle", 9, 52));
        lista.add(new Persona(753, "Maëlyss", "Imloch", "Acceso a datos", 8, 73));
        lista.add(new Persona(754, "Laurène", "Battrum", "NodeJs", 4, 20));
        lista.add(new Persona(755, "Bénédicte", "Bratt", "MySQL", 7, 66));
        lista.add(new Persona(756, "Mélodie", "Coomes", "BBDD", 8, 52));
        lista.add(new Persona(757, "Mélia", "Radbone", "BBDD", 5, 56));
        lista.add(new Persona(758, "Audréanne", "Malkinson", "JavaScript", 9, 55));
        lista.add(new Persona(759, "Lóng", "Hurt", "JavaScript", 6, 55));
        lista.add(new Persona(760, "Alizée", "Finch", "PostgreSQL", 10, 30));
        lista.add(new Persona(761, "Wá", "Josefson", "JavaScript", 1, 41));
        lista.add(new Persona(762, "Lyséa", "Dudin", "react", 8, 46));
        lista.add(new Persona(763, "Simplifiés", "Toretta", "react", 2, 62));
        lista.add(new Persona(764, "Adélie", "Giff", "XML", 8, 58));
        lista.add(new Persona(765, "Loïca", "Pinney", "XML", 8, 61));
        lista.add(new Persona(766, "Béatrice", "Haglington", "NodeJs", 7, 54));
        lista.add(new Persona(767, "Stéphanie", "Zanioletti", "PostgreSQL", 2, 21));
        lista.add(new Persona(768, "Sélène", "Hyams", "POO", 9, 57));
        lista.add(new Persona(769, "Bécassine", "Lethardy", "MySQL", 6, 73));
        lista.add(new Persona(770, "Dafnée", "Coare", "Angular", 5, 54));
        lista.add(new Persona(771, "Crééz", "Prine", "BBDD", 3, 72));
        lista.add(new Persona(772, "Uò", "Jennings", "PostgreSQL", 3, 20));
        lista.add(new Persona(773, "Salomé", "Dalrymple", "Oracle", 9, 41));
        lista.add(new Persona(774, "Måns", "Halleybone", "PostgreSQL", 1, 19));
        lista.add(new Persona(775, "Méghane", "Rawling", "Oracle", 3, 64));
        lista.add(new Persona(776, "Yè", "Sugar", "POO", 1, 59));
        lista.add(new Persona(777, "Mélanie", "Maybury", "PostgreSQL", 7, 54));
        lista.add(new Persona(778, "Yú", "Ship", "Angular", 2, 21));
        lista.add(new Persona(779, "Noëlla", "Gentile", "Express", 8, 73));
        lista.add(new Persona(780, "Bérengère", "Humberstone", "POO", 6, 44));
        lista.add(new Persona(781, "Daphnée", "Foddy", "sql", 3, 31));
        lista.add(new Persona(782, "Bérengère", "Scutchin", "MySQL", 6, 41));
        lista.add(new Persona(783, "Naéva", "Seaton", "JavaScript", 1, 72));
        lista.add(new Persona(784, "Yú", "Mynett", "Express", 5, 47));
        lista.add(new Persona(785, "Gaïa", "Petrello", "BBDD", 6, 55));
        lista.add(new Persona(786, "Laïla", "Langdon", "Express", 5, 40));
        lista.add(new Persona(787, "Cloé", "Hellwing", "XML", 3, 55));
        lista.add(new Persona(788, "Gösta", "Scrammage", "NodeJs", 7, 73));
        lista.add(new Persona(789, "Béatrice", "Thorrold", "MySQL", 3, 47));
        lista.add(new Persona(790, "Léone", "Vondruska", "BBDD", 7, 27));
        lista.add(new Persona(791, "Östen", "Grzegorczyk", "JavaScript", 4, 28));
        lista.add(new Persona(792, "Pénélope", "Carrivick", "XML", 4, 24));
        lista.add(new Persona(793, "Maï", "Toffoletto", "JavaScript", 4, 71));
        lista.add(new Persona(794, "Göran", "Izkovicz", "PostgreSQL", 10, 34));
        lista.add(new Persona(795, "Yóu", "Marzele", "Angular", 8, 55));
        lista.add(new Persona(796, "Gérald", "Showen", "odoo", 2, 67));
        lista.add(new Persona(797, "Almérinda", "Wraighte", "MySQL", 5, 70));
        lista.add(new Persona(798, "Ophélie", "Scallon", "Java", 6, 58));
        lista.add(new Persona(799, "Mà", "Slopier", "BBDD", 2, 39));
        lista.add(new Persona(800, "Åslög", "Dami", "Angular", 5, 68));
        lista.add(new Persona(801, "Pénélope", "Anfossi", "Oracle", 2, 59));
        lista.add(new Persona(802, "Gaëlle", "Jepson", "BBDD", 8, 21));
        lista.add(new Persona(803, "Céline", "Vanichev", "Java", 6, 56));
        lista.add(new Persona(804, "Agnès", "Risso", "Java", 1, 44));
        lista.add(new Persona(805, "Mélia", "Hindenburg", "BBDD", 5, 67));
        lista.add(new Persona(806, "Cécilia", "Morcomb", "PostgreSQL", 8, 44));
        lista.add(new Persona(807, "Åslög", "Colquite", "Java", 10, 43));
        lista.add(new Persona(808, "Bérangère", "Laetham", "BBDD", 3, 25));
        lista.add(new Persona(809, "Stévina", "Attree", "NodeJs", 7, 66));
        lista.add(new Persona(810, "Léonore", "Gonzales", "Acceso a datos", 1, 46));
        lista.add(new Persona(811, "Pélagie", "Craddy", "Acceso a datos", 8, 22));
        lista.add(new Persona(812, "Yénora", "Marchello", "Acceso a datos", 5, 32));
        lista.add(new Persona(813, "Maëlle", "Ashmore", "Acceso a datos", 9, 64));
        lista.add(new Persona(814, "Cécile", "Wayper", "Patrones de diseño", 6, 25));
        lista.add(new Persona(815, "Eliès", "Beccero", "Oracle", 1, 34));
        lista.add(new Persona(816, "Adèle", "Rutigliano", "POO", 4, 73));
        lista.add(new Persona(817, "Valérie", "Guyet", "POO", 6, 45));
        lista.add(new Persona(818, "Lài", "Cahalin", "BBDD", 9, 34));
        lista.add(new Persona(819, "Lyséa", "Gwilt", "Angular", 5, 19));
        lista.add(new Persona(820, "Anaïs", "Rowthorn", "Java", 8, 31));
        lista.add(new Persona(821, "Maëline", "Littlejohns", "odoo", 3, 30));
        lista.add(new Persona(822, "Léone", "Dikels", "MySQL", 2, 63));
        lista.add(new Persona(823, "Kévina", "Touzey", "NodeJs", 9, 66));
        lista.add(new Persona(824, "Maï", "Swaile", "Acceso a datos", 2, 43));
        lista.add(new Persona(825, "Maëline", "Fancourt", "NodeJs", 3, 46));
        lista.add(new Persona(826, "Kù", "Garthland", "MySQL", 8, 48));
        lista.add(new Persona(827, "Salomé", "Gwin", "BBDD", 1, 64));
        lista.add(new Persona(828, "Styrbjörn", "Magog", "react", 4, 31));
        lista.add(new Persona(829, "Eléonore", "Humbey", "Oracle", 1, 49));
        lista.add(new Persona(830, "Judicaël", "Kivelhan", "Oracle", 1, 57));
        lista.add(new Persona(831, "Östen", "Rosenstiel", "sql", 6, 45));
        lista.add(new Persona(832, "André", "Foley", "JavaScript", 8, 54));
        lista.add(new Persona(833, "Garçon", "Verman", "Patrones de diseño", 10, 50));
        lista.add(new Persona(834, "Cécile", "Towell", "POO", 10, 40));
        lista.add(new Persona(835, "Ráo", "Freschi", "Java", 3, 29));
        lista.add(new Persona(836, "Cléopatre", "Porritt", "Angular", 9, 53));
        lista.add(new Persona(837, "Gisèle", "Arkell", "odoo", 4, 48));
        lista.add(new Persona(838, "Clémentine", "Robiou", "Angular", 5, 56));
        lista.add(new Persona(839, "Maïwenn", "Toleman", "BBDD", 7, 70));
        lista.add(new Persona(840, "Clélia", "Cleverley", "Acceso a datos", 9, 75));
        lista.add(new Persona(841, "Noémie", "Jerromes", "POO", 1, 32));
        lista.add(new Persona(842, "Méghane", "Pietrasik", "Java", 5, 39));
        lista.add(new Persona(843, "Cléa", "Yewman", "Oracle", 6, 49));
        lista.add(new Persona(844, "Léonore", "Denisyev", "JavaScript", 5, 28));
        lista.add(new Persona(845, "Adélaïde", "MacDowal", "MySQL", 9, 67));
        lista.add(new Persona(846, "Cloé", "Carnie", "JavaScript", 4, 52));
        lista.add(new Persona(847, "Maïlis", "Roels", "Oracle", 2, 73));
        lista.add(new Persona(848, "Faîtes", "Kos", "Acceso a datos", 6, 69));
        lista.add(new Persona(849, "André", "Meeus", "XML", 9, 66));
        lista.add(new Persona(850, "Åslög", "Thormwell", "PostgreSQL", 4, 29));
        lista.add(new Persona(851, "Maëlla", "Sanchis", "Acceso a datos", 5, 37));
        lista.add(new Persona(852, "Léandre", "Davis", "sql", 7, 35));
        lista.add(new Persona(853, "Mélia", "Grishenkov", "JavaScript", 10, 25));
        lista.add(new Persona(854, "Céline", "Durward", "PostgreSQL", 7, 52));
        lista.add(new Persona(855, "Lyséa", "Manklow", "Java", 5, 52));
        lista.add(new Persona(856, "Mà", "Maginot", "sql", 9, 49));
        lista.add(new Persona(857, "Bérengère", "Illidge", "sql", 3, 19));
        lista.add(new Persona(858, "Zoé", "Rounsefell", "Acceso a datos", 7, 74));
        lista.add(new Persona(859, "Gérald", "Sayer", "react", 7, 18));
        lista.add(new Persona(860, "Vérane", "Morrott", "Java", 2, 30));
        lista.add(new Persona(861, "Bérénice", "McAnellye", "Angular", 2, 72));
        lista.add(new Persona(862, "Marie-françoise", "Ratazzi", "odoo", 7, 43));
        lista.add(new Persona(863, "Nélie", "Hammerberg", "XML", 1, 49));
        lista.add(new Persona(864, "Géraldine", "Belsham", "BBDD", 8, 62));
        lista.add(new Persona(865, "Börje", "McKitterick", "Java", 8, 36));
        lista.add(new Persona(866, "Clémentine", "Coole", "XML", 9, 27));
        lista.add(new Persona(867, "Sélène", "Gwyneth", "Angular", 7, 18));
        lista.add(new Persona(868, "Clémentine", "Evershed", "sql", 5, 29));
        lista.add(new Persona(869, "Desirée", "Jezzard", "Java", 5, 41));
        lista.add(new Persona(870, "Fèi", "Ventura", "Acceso a datos", 4, 39));
        lista.add(new Persona(871, "Kévina", "McGlaud", "NodeJs", 10, 25));
        lista.add(new Persona(872, "Adélaïde", "Rolfo", "XML", 9, 28));
        lista.add(new Persona(873, "Vérane", "Godsell", "MySQL", 5, 42));
        lista.add(new Persona(874, "Naëlle", "Meiklam", "Patrones de diseño", 2, 19));
        lista.add(new Persona(875, "Aloïs", "Goacher", "Express", 4, 20));
        lista.add(new Persona(876, "Célestine", "Janisson", "Angular", 8, 28));
        lista.add(new Persona(877, "Audréanne", "Blakeborough", "PostgreSQL", 6, 65));
        lista.add(new Persona(878, "André", "Seckom", "Java", 8, 44));
        lista.add(new Persona(879, "Marie-josée", "Ferie", "Express", 3, 42));
        lista.add(new Persona(880, "Mahélie", "Soars", "BBDD", 5, 41));
        lista.add(new Persona(881, "Zhì", "Matveyev", "XML", 4, 51));
        lista.add(new Persona(882, "Erwéi", "Thonason", "react", 6, 29));
        lista.add(new Persona(883, "Bérénice", "McGeorge", "POO", 8, 58));
        lista.add(new Persona(884, "Anaé", "Navarro", "PostgreSQL", 8, 57));
        lista.add(new Persona(885, "Maïté", "Ruddle", "POO", 3, 28));
        lista.add(new Persona(886, "Laurélie", "Tomalin", "NodeJs", 5, 72));
        lista.add(new Persona(887, "Naéva", "Cavil", "Express", 9, 55));
        lista.add(new Persona(888, "Björn", "Black", "Angular", 3, 27));
        lista.add(new Persona(889, "Annotée", "Jouhandeau", "Express", 8, 25));
        lista.add(new Persona(890, "Gwenaëlle", "Semmens", "Patrones de diseño", 6, 50));
        lista.add(new Persona(891, "Dafnée", "Iamittii", "POO", 5, 73));
        lista.add(new Persona(892, "Inès", "Clive", "XML", 7, 65));
        lista.add(new Persona(893, "Maëlann", "Imeson", "POO", 6, 65));
        lista.add(new Persona(894, "Agnès", "Schubuser", "Angular", 10, 44));
        lista.add(new Persona(895, "Börje", "Hanselman", "odoo", 7, 56));
        lista.add(new Persona(896, "Laurène", "Korba", "POO", 6, 49));
        lista.add(new Persona(897, "Mélissandre", "Boote", "XML", 3, 47));
        lista.add(new Persona(898, "Marie-thérèse", "Kemet", "Oracle", 7, 23));
        lista.add(new Persona(899, "Kévina", "Springett", "react", 2, 40));
        lista.add(new Persona(900, "Léana", "Raveau", "Acceso a datos", 3, 22));
        lista.add(new Persona(901, "Ráo", "Edmons", "sql", 4, 29));
        lista.add(new Persona(902, "Loïca", "Reinhardt", "Angular", 7, 37));
        lista.add(new Persona(903, "Mélodie", "Flintoft", "Java", 10, 20));
        lista.add(new Persona(904, "Camélia", "Curee", "Patrones de diseño", 5, 34));
        lista.add(new Persona(905, "Néhémie", "Sanbrooke", "odoo", 6, 21));
        lista.add(new Persona(906, "Yú", "Lagden", "XML", 4, 71));
        lista.add(new Persona(907, "Torbjörn", "Thistleton", "odoo", 3, 60));
        lista.add(new Persona(908, "Intéressant", "MacNelly", "PostgreSQL", 6, 37));
        lista.add(new Persona(909, "Méghane", "O'Kennavain", "Express", 2, 68));
        lista.add(new Persona(910, "Cloé", "Obray", "Java", 3, 55));
        lista.add(new Persona(911, "Miléna", "Matias", "react", 6, 31));
        lista.add(new Persona(912, "Maïlys", "Wellsman", "PostgreSQL", 9, 51));
        lista.add(new Persona(913, "Naéva", "Leng", "Express", 7, 36));
        lista.add(new Persona(914, "Maëlle", "Pidler", "PostgreSQL", 3, 23));
        lista.add(new Persona(915, "Yóu", "Coenraets", "react", 6, 28));
        lista.add(new Persona(916, "Kuí", "Caplen", "POO", 7, 45));
        lista.add(new Persona(917, "Nadège", "Sybbe", "Oracle", 6, 18));
        lista.add(new Persona(918, "Erwéi", "Agostini", "Angular", 3, 30));
        lista.add(new Persona(919, "Esbjörn", "Wixey", "sql", 5, 63));
        lista.add(new Persona(920, "Clémence", "Sallans", "Express", 9, 31));
        lista.add(new Persona(921, "Intéressant", "Renshaw", "Oracle", 4, 71));
        lista.add(new Persona(922, "Loïc", "Charnock", "Oracle", 9, 44));
        lista.add(new Persona(923, "Börje", "Itzkovwitch", "MySQL", 3, 36));
        lista.add(new Persona(924, "Marie-hélène", "McEvilly", "Express", 7, 22));
        lista.add(new Persona(925, "Hélèna", "Tosh", "JavaScript", 2, 51));
        lista.add(new Persona(926, "Médiamass", "Beed", "JavaScript", 4, 52));
        lista.add(new Persona(927, "Léandre", "Gallager", "Java", 6, 22));
        lista.add(new Persona(928, "Desirée", "Tuffs", "PostgreSQL", 6, 49));
        lista.add(new Persona(929, "Yóu", "Crome", "odoo", 6, 23));
        lista.add(new Persona(930, "Crééz", "Skilling", "Acceso a datos", 4, 26));
        lista.add(new Persona(931, "Séverine", "Tuminelli", "BBDD", 2, 62));
        lista.add(new Persona(932, "Renée", "Ivison", "sql", 6, 40));
        lista.add(new Persona(933, "Gérald", "Kneeland", "Patrones de diseño", 10, 64));
        lista.add(new Persona(934, "Marie-hélène", "Trenoweth", "MySQL", 6, 42));
        lista.add(new Persona(935, "Kallisté", "Gerber", "Acceso a datos", 5, 48));
        lista.add(new Persona(936, "Simplifiés", "Stobo", "sql", 7, 52));
        lista.add(new Persona(937, "Adèle", "Attril", "JavaScript", 7, 24));
        lista.add(new Persona(938, "Mélinda", "Frude", "odoo", 8, 38));
        lista.add(new Persona(939, "Joséphine", "Medland", "JavaScript", 10, 26));
        lista.add(new Persona(940, "Frédérique", "Wager", "odoo", 1, 72));
        lista.add(new Persona(941, "Renée", "Sibary", "Java", 8, 71));
        lista.add(new Persona(942, "Maëlyss", "Ratcliff", "odoo", 6, 61));
        lista.add(new Persona(943, "Marie-noël", "Bernaert", "MySQL", 6, 54));
        lista.add(new Persona(944, "Marlène", "Brazil", "sql", 7, 21));
        lista.add(new Persona(945, "Angèle", "Milborn", "Oracle", 5, 45));
        lista.add(new Persona(946, "Vénus", "Mucklo", "POO", 10, 64));
        lista.add(new Persona(947, "Solène", "Rodrigues", "JavaScript", 4, 28));
        lista.add(new Persona(948, "Mylène", "Cornock", "Java", 7, 61));
        lista.add(new Persona(949, "Médiamass", "Domleo", "Express", 2, 18));
        lista.add(new Persona(950, "Dà", "Merrett", "Oracle", 2, 28));
        lista.add(new Persona(951, "Céline", "Spavon", "Acceso a datos", 9, 68));
        lista.add(new Persona(952, "Mélys", "Airton", "BBDD", 1, 21));
        lista.add(new Persona(953, "Maïwenn", "Crosher", "Express", 3, 42));
        lista.add(new Persona(954, "Táng", "Paynes", "JavaScript", 9, 66));
        lista.add(new Persona(955, "Dù", "Regelous", "PostgreSQL", 4, 59));
        lista.add(new Persona(956, "Cunégonde", "Baudains", "Express", 5, 75));
        lista.add(new Persona(957, "Mélia", "Adshad", "POO", 4, 21));
        lista.add(new Persona(958, "Mélanie", "Lafont", "Acceso a datos", 10, 67));
        lista.add(new Persona(959, "Angèle", "Aimable", "POO", 4, 55));
        lista.add(new Persona(960, "Marie-thérèse", "Impleton", "PostgreSQL", 1, 26));
        lista.add(new Persona(961, "Anaïs", "Dibley", "NodeJs", 8, 58));
        lista.add(new Persona(962, "Agnès", "Scatchard", "BBDD", 6, 43));
        lista.add(new Persona(963, "Zoé", "Abbot", "XML", 6, 19));
        lista.add(new Persona(964, "Marie-françoise", "Cloake", "POO", 8, 41));
        lista.add(new Persona(965, "Gaétane", "Berkeley", "POO", 4, 60));
        lista.add(new Persona(966, "Zoé", "Schusterl", "Java", 2, 52));
        lista.add(new Persona(967, "Françoise", "Seabon", "sql", 5, 72));
        lista.add(new Persona(968, "Andréanne", "Gorch", "Acceso a datos", 4, 34));
        lista.add(new Persona(969, "Adèle", "Herreros", "XML", 9, 18));
        lista.add(new Persona(970, "Nadège", "Proffitt", "Express", 10, 26));
        lista.add(new Persona(971, "Bénédicte", "Siggers", "react", 8, 74));
        lista.add(new Persona(972, "Maïté", "Reboul", "PostgreSQL", 3, 31));
        lista.add(new Persona(973, "Michèle", "Alcorn", "Java", 7, 53));
        lista.add(new Persona(974, "Garçon", "Robens", "Patrones de diseño", 7, 20));
        lista.add(new Persona(975, "Séréna", "Fontell", "Patrones de diseño", 8, 34));
        lista.add(new Persona(976, "Andrée", "Digan", "POO", 4, 75));
        lista.add(new Persona(977, "Andrée", "D'Andrea", "PostgreSQL", 5, 64));
        lista.add(new Persona(978, "Lorène", "Ivens", "PostgreSQL", 3, 63));
        lista.add(new Persona(979, "Gösta", "Groucutt", "Patrones de diseño", 7, 27));
        lista.add(new Persona(980, "Zoé", "Porson", "PostgreSQL", 1, 44));
        lista.add(new Persona(981, "Marie-josée", "Hornbuckle", "Angular", 2, 24));
        lista.add(new Persona(982, "Marlène", "Haresnape", "odoo", 5, 62));
        lista.add(new Persona(983, "Alizée", "Fulford", "XML", 5, 36));
        lista.add(new Persona(984, "Cloé", "Grigoli", "NodeJs", 2, 26));
        lista.add(new Persona(985, "Joséphine", "Okroy", "Oracle", 7, 75));
        lista.add(new Persona(986, "Marie-françoise", "Hunnicutt", "XML", 6, 52));
        lista.add(new Persona(987, "Noëlla", "Kynett", "Oracle", 3, 50));
        lista.add(new Persona(988, "Maïté", "Dutteridge", "odoo", 6, 28));
        lista.add(new Persona(989, "Lóng", "Noden", "MySQL", 8, 30));
        lista.add(new Persona(990, "Börje", "Ahmed", "odoo", 7, 39));
        lista.add(new Persona(991, "Gösta", "Jenoure", "sql", 2, 70));
        lista.add(new Persona(992, "Vérane", "Vercruysse", "JavaScript", 7, 71));
        lista.add(new Persona(993, "Maëlle", "Guile", "Java", 5, 64));
        lista.add(new Persona(994, "Görel", "Sawden", "Oracle", 7, 67));
        lista.add(new Persona(995, "Salomé", "Very", "JavaScript", 5, 33));
        lista.add(new Persona(996, "Célia", "Timmes", "Patrones de diseño", 5, 71));
        lista.add(new Persona(997, "Naëlle", "Balls", "Angular", 5, 56));
        lista.add(new Persona(998, "Maëlys", "Fabbri", "Patrones de diseño", 10, 32));
        lista.add(new Persona(999, "Mahélie", "Laughlan", "Java", 7, 34));
        lista.add(new Persona(1000, "Céline", "Rosborough", "sql", 10, 22));
        return lista;
    }

}
